apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:tCd5OW6FTu44qK7NyBlxhq+Z57X8hWD6k+zES97MyqE4Q9ql8N9YLQ==,iv:oGK27py2BdmoNZiRrM1wDSU8v3wrdLKdxR6/pRQz7+s=,tag:AygdYnN595zim20meUsG/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaWJaVDBHTjJ2R0lmSWhz
            T0krYmNISm03dTA1WE9rMHhFeW40ZE1uaUJjCmRNZU56czJRZVYwcUJ3QU94OVg3
            Tk51VWZETTRCYWE4OGs3T21VRlo0WDgKLS0tIDRvZUxwTVZkYjRYRFJZQXcxMzRR
            bzlEVE5aY2UyM3RvUXdmSmY2N29nNDAKRIfp63yBShAYxSmGp76NjJ/0RQPDd9Rn
            CcFQFEfocrN2u4Lmnbe+hto44MyhKpQLQiNKtFqrheTM6SVyNk/bPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T17:21:21Z"
    mac: ENC[AES256_GCM,data:AAN/CsQopo3edZt66++2/LpslPvD+jG/IG+R55KT0Vy54DVusPPG8tqbJrKhg0ZB80107OkkU+uFyuz3DDJS1td4S8I4Ne7Q0qIYMUsEDHjyRIwRh6VMWWThiEp8U/qQQJZynHAmPJhk6BIes/mhM9LX4zBKi6fhWhPJan2iz6I=,iv:F2to4CLDDOqerF5flBpHY0jrLDtRsyUdtUbHUTHtIU0=,tag:JwKsxBuen7H3gsMy+oNS1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
